Update integrationtests.yml

diff --git a/.github/workflows/integrationtests.yml b/.github/workflows/integrationtests.yml
--- a/.github/workflows/integrationtests.yml
+++ b/.github/workflows/integrationtests.yml
@@ -90,33 +90,7 @@ jobs:
             echo "Error: Failed to generate a response using the model. HTTP Status Code: $http_code"
             exit 1
           fi
-
-      # Step 9: Check main server readiness
-      - name: Check main server readiness
-        run: |
-            echo "Checking if the main server is up..."
-            expected_message="The server is up and running!"
-            end=$((SECONDS+1200)) # Wait up to 20 minutes
-            while [ $SECONDS -lt $end ]; do
-              response=$(curl -s -o response_body.txt -w "%{http_code}" http://localhost:8000)
-              http_code="${response: -3}" # Extract HTTP status code
-              body=$(cat response_body.txt)
-            
-              echo "HTTP Status Code: $http_code"
-              echo "Response Body: $body"
-            
-              if [ "$http_code" -eq 200 ] && [[ "$body" == *"$expected_message"* ]]; then
-                echo "Main server is running!"
-                exit 0
-              fi
-            
-              echo "Waiting for main server readiness..."
-              sleep 5
-            done
-            
-            echo "Error: Main server did not start within 20 minutes."
-            exit 1
-
+          
       # Step 10: Check server logs if readiness fails
       - name: Check Main Server Logs
         run: |
@@ -127,6 +101,33 @@ jobs:
               exit 1
             fi
             docker logs "$container_id"
+
+      # Step 11: Check main server readiness
+      - name: Check main server readiness
+        run: |
+          echo "Checking if the main server is up..."
+          expected_message="The server is up and running!"
+          end=$((SECONDS+1200)) # Wait up to 20 minutes
+          while [ $SECONDS -lt $end ]; do
+            response=$(curl -s -o response_body.txt -w "%{http_code}" http://localhost:8000)
+            http_code="${response: -3}" # Extract HTTP status code
+            body=$(cat response_body.txt)
+
+            echo "HTTP Status Code: $http_code"
+            echo "Response Body: $body"
+
+            if [ "$http_code" -eq 200 ] && [[ "$body" == *"$expected_message"* ]]; then
+              echo "Main server is running!"
+              exit 0
+            fi
+
+            echo "Waiting for main server readiness..."
+            sleep 5
+          done
+
+          echo "Error: Main server did not start within 20 minutes."
+          exit 1
+      
 
       # Step 11: Run Integration Tests
       - name: Run Python Integration Tests
