Update integrationtests.yml

diff --git a/.github/workflows/integrationtests.yml b/.github/workflows/integrationtests.yml
--- a/.github/workflows/integrationtests.yml
+++ b/.github/workflows/integrationtests.yml
@@ -28,23 +28,7 @@ jobs:
           PROJECT_ROOT: ${{ github.workspace }}
         run: docker-compose up -d
 
-      # Step 4: Test if the server is up
-      - name: Test server with curl
-        run: |
-          end=$((SECONDS+120))
-          while [ $SECONDS -lt $end ]; do
-            if curl -s http://localhost:8000 > /dev/null; then
-              echo "Server is up!"
-              exit 0
-            else
-              echo "Waiting for server to be up..."
-              sleep 5
-            fi
-          done
-          echo "Error: Server did not start within 2 minutes."
-          exit 1
-
-       # Step 5: Check if Ollama server is up
+      # Step 4: Check if Ollama server is up
       - name: Check Ollama server status
         run: |
           end=$((SECONDS+120))  # Wait up to 2 minutes
@@ -59,6 +43,22 @@ jobs:
           done
           echo "Error: Ollama server did not start within 2 minutes."
           exit 1
+
+      # Step 5: Test if the server is up
+      - name: Test server with curl
+        run: |
+          end=$((SECONDS+120))
+          while [ $SECONDS -lt $end ]; do
+            if curl -s http://localhost:8000 > /dev/null; then
+              echo "Server is up!"
+              exit 0
+            else
+              echo "Waiting for server to be up..."
+              sleep 5
+            fi
+          done
+          echo "Error: Server did not start within 2 minutes."
+          exit 1       
 
       # Step 6: Pull the Llama model
       - name: Pull Llama model
@@ -75,7 +75,7 @@ jobs:
             echo "Failed to pull model. Exiting."
             exit 1
           fi
-          
+
       # Step 7: Test model response
       - name: Test model response
         run: |
