Update integrationtests.yml

diff --git a/.github/workflows/integrationtests.yml b/.github/workflows/integrationtests.yml
--- a/.github/workflows/integrationtests.yml
+++ b/.github/workflows/integrationtests.yml
@@ -26,23 +26,7 @@ jobs:
         working-directory: src/backend
         run: docker-compose up -d
 
-      # Step 4: Test if the server is up
-      - name: Test server with curl
-        run: |
-          end=$((SECONDS+120))
-          while [ $SECONDS -lt $end ]; do
-            if curl -s http://localhost:8000 > /dev/null; then
-              echo "Server is up!"
-              exit 0
-            else
-              echo "Waiting for server to be up..."
-              sleep 5
-            fi
-          done
-          echo "Error: Server did not start within 2 minutes."
-          exit 1
-
-      # Step 5: Verify Ollama Server is Running
+      # Step 4: Verify Ollama Server is Running
       - name: Check Ollama server health
         run: |
           echo "Checking if Ollama server is up..."
@@ -59,11 +43,11 @@ jobs:
           echo "Error: Ollama server did not start within 3 minutes."
           exit 1
 
-      # Step 6: List all running containers
+      # Step 5: List all running containers
       - name: List all running containers
         run: docker ps
 
-      # Step 7: Check Ollama server logs
+      # Step 6: Check Ollama server logs
       - name: Check Ollama server logs
         run: |
           container_id=$(docker ps -q --filter "ancestor=ollama/ollama:0.4.1")
@@ -74,7 +58,7 @@ jobs:
           echo "Fetching logs for container: $container_id"
           docker logs "$container_id"
 
-      # Step 8: Pull llama3.2:3b model
+      # Step 7: Pull llama3.2:3b model
       - name: Pull llama3.2:3b model
         run: |
           echo "Pulling llama3.2:3b model..."
@@ -87,7 +71,7 @@ jobs:
           fi
           echo "Llama 3.2 3B model has been successfully initiated for download."
 
-      # Step 9: Test AI Responses
+      # Step 8: Test AI Responses
       - name: Test AI Responses
         run: |
           echo "Testing AI response..."
@@ -106,6 +90,22 @@ jobs:
             echo "Error: Failed to generate a response using the model. HTTP Status Code: $http_code"
             exit 1
           fi
+
+      # Step 9: Test if the server is up
+      - name: Test server with curl
+        run: |
+          end=$((SECONDS+120))
+          while [ $SECONDS -lt $end ]; do
+            if curl -s http://localhost:8000 > /dev/null; then
+              echo "Server is up!"
+              exit 0
+            else
+              echo "Waiting for server to be up..."
+              sleep 5
+            fi
+          done
+          echo "Error: Server did not start within 2 minutes."
+          exit 1
 
       # Step 10: Run Integration Tests
       - name: Run Python Integration Tests
