Update integrationtests.yml

diff --git a/.github/workflows/integrationtests.yml b/.github/workflows/integrationtests.yml
--- a/.github/workflows/integrationtests.yml
+++ b/.github/workflows/integrationtests.yml
@@ -77,14 +77,7 @@ jobs:
             echo "Docker build failed. Exiting..."
             exit 1
           }
-          echo "Docker image chat_service_image built successfully."
-          
-          echo "Building Docker image test_image"
-          docker build -t test_image:latest -f ${PROJECT_ROOT}/build/test_docker/Dockerfile ${PROJECT_ROOT} || {
-            echo "Docker build failed for test_image. Exiting..."
-            exit 1
-          }
-          echo "Docker image test_image built successfully."   
+          echo "Docker image chat_service_image built successfully."  
 
       # Step 8: Run Docker Compose
       - name: Run docker-compose up
@@ -123,7 +116,20 @@ jobs:
             fi
           done
           echo "Error: Server did not start within 2 minutes."
-          exit 1  
+          exit 1
+
+      # Step 11: Build test Docker image
+      - name: Build test Docker image
+        working-directory: src/backend
+        env:
+          PROJECT_ROOT: ${{ github.workspace }}
+        run: |
+          echo "Building Docker image test_image"
+          docker build -t test_image:latest -f ${PROJECT_ROOT}/build/test_docker/Dockerfile ${PROJECT_ROOT} || {
+            echo "Docker build failed for test image. Exiting..."
+            exit 1
+          }
+          echo "Docker image test_image built successfully."    
 
       # Step 12: Test model response
       - name: Test model response
