modified test and deploy.yml

diff --git a/.github/workflows/test_and_deploy.yml b/.github/workflows/test_and_deploy.yml
--- a/.github/workflows/test_and_deploy.yml
+++ b/.github/workflows/test_and_deploy.yml
@@ -39,6 +39,12 @@ jobs:
           curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
           echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
           sudo apt update && sudo apt install ngrok
+          if [ -z "${{ secrets.NGROK_AUTH_TOKEN }}" ]; then
+            echo "❌ NGROK_AUTH_TOKEN is missing!"
+            exit 1
+          else
+            echo "✅ NGROK_AUTH_TOKEN is set."
+          fi
           ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
 
       - name: Start Backend Service
